theme: jekyll-theme-minimal
#remote_theme: b2a3e8/jekyll-theme-console

locale                   : "ko" # 타깃 국가 설정
title                    : "INU Operating Systems Laboratory" # 블로그 좌측상단의 제목
name                     : "INU OSLab"
description              : "Website for INU Operating Systems Laboratory"
url                      : "https://inuoslab.github.io" # 블로그 주소
#repository               : "inuoslab/inuoslab.github.io" # 블로그 github 리포지토리
logo                     : "/assets/images/inuoslab_small_icon.jpg"
#search                   : true # 사이트 우측 상단 검색 활성화
#search_full_content      : false # 제목이 아닌 내용까지도 검색할 것인지에 대한 설정 기본 false
#show_downloads           : true

header_pages:
  - index:
    name: Home
    url: index
  - members:
    name: Members
    url: members
  - research:
    name: Research
    url: research
  - news:
    name: News
    url: news


# style: light # light, dark, hacker for theme-console 

footer: 'Operating Systems Laboratory, <a href="https://inu.ac.kr/">INU</a>, Songdo, Incheon, KR.'
 
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true # 해당 포스트를 읽은 시간이 표시되는데 기본값은 true이다.
      comments: true # true
      share: false # true # 포스트 공유 기능을 활성화 할 것인지 정한다. 기본값은 true이다.
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false